charmbracelet/bubbletea

examples/http/main.go

Hi. I'd noticed that the `/examples/http/main.go` program has an incorrect program description comment. It's using the same description comment as the `/examples/simple/main.go` program. This PR fixes it.

Fix incorrect program description comment

---

README.md
tutorials/basics/README.md
tutorials/commands/README.md

Some links to pkg.go.dev in the documentation seems incorrect, so fixed.

Fix links in documents

---

screen.go
tea.go
tty.go

In some rare cases a user may want to hide the cursor. This PR addresses that.
In particular, this is being added to address charmbracelet/glow#214.

Manual hide cursor command + subtle cursor hide/show engineering improvements

---

go.mod
tea.go

This PR allows the user to set a custom input and output. In addition it handles the case where the input returns an io.EOF error. There are cases eg. piping where os.Stdin may be empty when bubbletea starts.
An alternative  (or even additional) implementation would be to allow rendering without reading from the input at all. 
Signed-off-by: Christoph Hartmann <chris@lollyrock.com>

allow custom input/output and handle eof for os.input properly

---

go.mod
go.sum
renderer.go

This will prevent rendering issues that could occur when the terminal automatically wraps long lines.
Do note that for more precise control you can truncate long lines yourself. We recommend the [`truncate`](https://pkg.go.dev/github.com/muesli/reflow/truncate) package in [Reflow](https://github.com/muesli/reflow), which Bubble Tea is using internally.

Automatically trim lines wider than the window width

---

commands.go
commands_test.go

The idea is to produce a single command that sequentially runs the given commands, returning the first non-nil msg.
Useful for things like saving the current state before quitting, or saving something and then refreshing a list...
Extracted from: https://github.com/caarlos0/tasktimer

Add a tea.Sequentially command

---

logging.go

Right now the logs read `prefix2021/02/01…`. This PR adds a space if one doesn't exist at the end of the prefix, so logs will now read `prefix 2021/02/01…`.

Add space after prefix if one doesn't exist

---

renderer.go

Fix race by acquiring the mutex before accessing renderer.buf in flush.
WARNING: DATA RACE
Read at 0x00c0000ee0a0 by goroutine 11:
bytes.(*Buffer).Len()
/home/chlunde/opt/go/src/bytes/buffer.go:73 +0x64
github.com/charmbracelet/bubbletea.(*renderer).flush()
/home/chlunde/src/bubbletea/renderer.go:91 +0x45
github.com/charmbracelet/bubbletea.(*renderer).listen()
/home/chlunde/src/bubbletea/renderer.go:76 +0x185
Previous write at 0x00c0000ee0a0 by main goroutine:
bytes.(*Buffer).Reset()
/home/chlunde/opt/go/src/bytes/buffer.go:98 +0xf5
github.com/charmbracelet/bubbletea.(*renderer).write()
/home/chlunde/src/bubbletea/renderer.go:195 +0x13c
github.com/charmbracelet/bubbletea.(*Program).Start()
/home/chlunde/src/bubbletea/tea.go:330 +0xbbb
main.main() …

Avoid race on renderer.buf in flush vs. write

---

examples/pipe/main.go
tea.go
tty.go
tty_unix.go
tty_windows.go

This PR automatically opens a TTY for input if input is not a TTY. In practice, this means that if you pipe or redirect data into a Bubble Tea application it will “just work.” Note that if the user has explicitly set the input (via `tea.WithInput`) a TTY will not be opened.
Also note that this PR includes Windows support. On Windows we open a console process for input (`CONIN$`) which is effectively the same as a TTY on unix in this case.
An example illustrating this new functionality has been added in the `examples/pipe` directory.
Related: #39 (where we introduced custom inputs) and #24 (where there's an argument to always open a TTY for input) and #41 (which contains a proposed solution).

Automatically open a TTY if needed

---

key.go

This update adds some type safety and flexibility to the `Key` and `KeyMsg` types. While it's technically a breaking change, we expect it affect very few applications, if any.

Implement String() on type Key and make key constants type KeyType

---

tea.go

This can fix #63 but cause a breaking change.

WithOutput option should take io.Writer as argument type.

---

standard_renderer.go

Lock the mutex before checking the buffer's length / content.

Mutex protect buffer access in standard renderer

---

standard_renderer.go

When using the standard renderer, this PR clears the bottom line before exiting a program. With inline programs, that final line is where the prompt will be drawn, so we need to clear that line to avoid situations where the prompt is overlaid onto part of the TUI.

Clear the bottom line before exiting to make room for the prompt

---

standard_renderer.go

Remove redundant lock in standard renderer listen.
And we can close `r.done` directly in this case, because we only send `struct{}{}` to `r.done` once.

Remove redundant lock in standard renderer listen

---

examples/http/main.go

recursive call e.Error() leads to stack overflow.

Fix stack overflow in examples/http

---

README.md

The "projects in the wild" list probably just keeps growing, let's move it towards the bottom of the README.

Add lipgloss to README links, move projects below it

---

examples/mouse/main.go
tea.go

This PR improves mouse support and deprecates mouse and altscreen program-level methods in favor of commands.
* Added `EnableMouseCellMotion`, `EnableMouseAllMotion` and `DisableMouse` commands for enabling and disabling the mouse.
* Mouse modes are automatically disabled when quitting a program.
* Program-level mouse methods are now deprecated: `Program.EnableMouseCellMotion`, `Program.DisableMouseCellMotion`, `Program.EnableMouseAllMotion`, `Program.DisableMouseAllMotion`. Use the new commands instead.
* Program-level altscreen methods are now deprecated: `Program.EnterAltScreen` and `Program.ExitAltScreen`. Use the corresponding commands instead.
* Mouse modes are automatically disabled when exiting after a panic.

Mouse Commands

---

tea.go

This is a minor tidying-up PR that pulls batch command processing into the main switch that handles internal messages in the Bubble Tea runtime. Previously, batch command processing was handled adjacent to internal message processing in an `if` type check.
This PR has no impact on either the API, nor performance.

Batch Processing Tidy-Up

---

renderer.go
standard_renderer.go

This PR introduces a performance optimization in the Bubble Tea standard renderer where only lines that have changed since the last render will be cleared and drawn.
Note that there's already an optimization in place that will skip renders entirely if nothing has changed.

Only render lines that have changed

---

standard_renderer.go

If the number of lines increased there's a chance that the increase in lines caused the terminal to scroll (even in the altscreen). Because of this we must repaint everything, as skipping lines will mis-render.
Thanks to @fiws for finding this bug.

Re-render all lines if the total number of lines increases

---

examples/result/main.go

Changes ```chose``` to ```close``` on line **32**

Fix typo in examples/result

---

nil_renderer.go
renderer.go
standard_renderer.go
tea.go

v0.13.4 introduced a regression where lines weren't always cleared when resizing the window, resulting in the occasional presence of rendering artifacts. This commit fixes that.

Force a full repaint when resizing the window

---

examples/fullscreen/main.go
examples/mouse/main.go
examples/pager/main.go
nil_renderer.go
renderer.go
standard_renderer.go
tea.go

This PR introduces three new `ProgramOption`s for starting programs with the altscreen and mouse enabled:
```go
// New! This is the recommended way to start your program with the mouse and altscreen active.
p := tea.NewProgram(model, tea.WithAltScreen(), tea.WithMouseAllMotion())
// Deprecated as this will only operate on stdout, as opposed to a custom output you may have set.
p := tea.NewProgram(model)
p.EnableAltScreen()
p.EnableMouseAllMotion()
// Strongly discouraged as these commands could be sent before starting  the renderer, resulting
// in rendering artifacts. This is due to the fact that commands run asynchronously in a goroutine.
func (m model) Init() tea.Cmd {
return tea.Batch(tea.EnterAltScreen, tea.EnableMouseAllMotion)
}
```
Also included are subtle rendering improvements …

Bugfixes: Races and Rendering

---

standard_renderer.go

This PR fixes a bug where lines requested to be ignored weren't always honored by the renderer due to some simple logical errors.
The bug became apparent with the the [Bubbles Viewport](https://github.com/charmbracelet/bubbles#viewport) with high performance scrolling enabled, which effectively allowed a race to ensue between the main renderer and the performance scroll renderer, resulting in random empty lines.

Fix a bug where explicitly ignored lines weren't honored by the renderer

---

examples/go.sum
go.mod
go.sum
options.go
tea.go
tty.go
tty_unix.go
tty_windows.go
tutorials/go.mod
tutorials/go.sum

This update allows Bubble Tea to accept a wider range of input types such as PTYs from SSH connections. Additionally, `WithInputTTY`, a new `ProgramOption`, has been added for explicitly requesting a new TTY (or console on Windows) to be opened for input.
The codebase has also grown quite a bit since it's initial release! To that end, this update includes some tidying up under the hood.
* Bubble Tea will now work with a wider range of inputs, such as PTYs
* Program option `WithInputTTY` will explicitly open a new TTY for input on unix systems or console on Windows (`CONIN$`)
* Programs will no longer panic when receiving messages during shutdown

More Inclusive Inputs

---

signals_unix.go
tty_unix.go

At Charm, we’re all about hot, new styles. That’s why we’re proud to introduce Go 1.17 build tags into Bubble Tea.

Add Go 1.17 build tags syntax

---

examples/go.mod
examples/go.sum
examples/pager/main.go

This update fixes a small miscalculation in the `pager` example when the performance `viewport` is in use. Bubbles has also been pinned to master for some `viewport` fixes.

Fix a performance rendering size miscalculation in the pager example

---

cancelreader_windows.go
signals_windows.go
tty_windows.go

This update sets `ENABLE_VIRUTAL_TERMINAL_INPUT` on Windows to fix a regression introduced in #120 which prevents the arrow keys on Windows from being read. As a bonus side effect, mouse events are now available to Bubble Tea programs in Windows.
Unfortunately, this update also nullifies `cancelReader`'s ability to cancel input on Windows. A solution, however, is in the works.
Closes #103.

Set ENABLE_VIRUTAL_TERMINAL_INPUT on Windows

---

options.go
standard_renderer.go
tea.go

To enable the ANSICompressor use the `WithANSICompressor()` program option:
```go
tea.NewProgram(model, tea.WithANSICompressor())
```

ANSI compression is now opt-in

---

examples/list-simple/main.go

This is a small update to remove some of the unused filtering stuff from the simple list example in order to keep it…simple.

Remove unused filtering stuff from simple list example

---

tutorials/commands/README.md

Remove extra word in commands README

---

cancelreader_bsd.go

and fix "in switch on ident (mismatched types uint64 and uint32)" error
when building for 32-bit bsd

Add cancelreader bsd go1.17 compilation flags

---

cancelreader_bsd.go
cancelreader_default.go
cancelreader_select.go

I'm noticing `dragonfly` build tags are missing in places where we otherwise support BSD. This update corrects that.

Add dragonfly build tags where appropriate

---

tutorials/commands/README.md

Slightly related: https://github.com/charmbracelet/bubbletea/pull/164/files
Although I think this PR fixes it more in line with the main README using Markdown variables instead of hardcoding the links.
The link in `[source]` was missing `tree/` which ended up in a 404. This can be seen by clicking 'on GitHub' in the first paragraph [here](https://github.com/charmbracelet/bubbletea/blob/master/tutorials/commands/README.md).
Also the `[bubbles]`, `[docs]` and `[examples]` variables were missing from this README. They're present in the main one [here](https://github.com/charmbracelet/bubbletea/blob/master/README.md?plain=1#L255-L256) and [here](https://github.com/charmbracelet/bubbletea/blob/master/README.md?plain=1#L266) but were just showing as unformatted when viewing the [commands …

Fix links in commands README

---

standard_renderer.go

This update fixes an issue where toggling the altscreen results in a blank screen if the return value of the `View` has not changed.
Closes #183.

Always redraw when toggling the altscreen

---

.github/workflows/lint-soft.yml
.github/workflows/lint.yml
.golangci-soft.yml
.golangci.yml
tty_unix.go

Soft-enforced linters will only annotate code changes, hard-enforced linters actually make the workflow fail if they encounter an issue.
You can run the soft linters manually on your machine:
```bash
golangci-lint run --config .golangci-soft.yml
```

Add separate sets of hard- and soft-enforced linters

---

examples/list-default/main.go

- Application has been handling `Ctrl+c`, but not doing anything. So fixed it to exit the program like any other apps.
- Fix to use `WithAltScreen` option instead of the deprecated `EnterAltScreen`.

Fix list-default example

---

README.md

Renamed sqlite-tui to termdbms and added gh-prs a wonderful gh-cli extension.

Rename termdbms and add gh-prs to BubbleTea-powered programs

---

examples/help/main.go
examples/list-default/main.go
examples/list-fancy/main.go
examples/list-simple/main.go
examples/paginator/main.go
examples/pipe/main.go
examples/progress-animated/main.go
examples/progress-static/main.go
examples/realtime/main.go
examples/send-msg/main.go
examples/spinner/main.go
examples/spinners/main.go
examples/textinput/main.go
examples/textinputs/main.go
examples/tui-daemon-combo/main.go

As of Bubbles `v0.10.0` the convention has changed from `NewModel` to `New`. `NewModel` will still work for now, in a deprecated fashion, in packages where it existed previously.

Migrate from `NewModel()` to `New()` in examples for Bubbles-related stuff

---

tea.go

Race condition bug: Start() is called in a new gorotuine, then Send(). If the Send happens before the msgs channel is allocated, the message is dropped.
Instead allocate the channel in the constructor, so msgs is never nil.

fix(tea): allocate msgs channel in constructor

---

tutorials/commands/README.md

Point to the actual source, not the tutorial itself.

Fix source link in Commands tutorial

---

examples/go.mod
examples/go.sum
go.mod
go.sum
tutorials/go.sum

This fixes an issue with broken/fake terminals not responding to OSC queries.
See discussion on minio/mc#3938.

Bump termenv to v0.11.0

---

commands.go

There are functions which may or may not return a `tea.Cmd` when they're done. Currently, I have to handle these nil values myself, leading to a lot of extra code.
It would be fantastic if `tea.Sequentially` would handle this for me.

Handle nil cmds in tea.Sequentially

---

commands_test.go
tea.go

feat: tea.Batch returns nil if all cmds are nil

---

examples/send-msg/main.go

This drops the goroutine the `tea.Program` was running in. As David Mytton pointed out this prevents a kind of race condition where the program isn't running yet and the first message can't be delivered.

Simplify send-msg example

---

standard_renderer.go
tea.go

* Add Kill() to force kill the program from the outside
* Prevent renderer channel from being closed multiple times

feat: kill the program and restore terminal state

---

key.go
key_test.go
mouse.go
mouse_test.go
tea.go

Mouse events may trigger more than a single event simultaneously.
Fixes #212.

Support receiving batched mouse events

---

tea.go

If output isn't a terminal, we can't retrieve the size of terminal. Trying to do so causes an ioctl error.

fix: don't check terminal size if we're not writing to a terminal

---

examples/go.sum
go.mod
go.sum
tutorials/go.sum

current version breaks builds for windows/arm64  
refs https://github.com/muesli/termenv/pull/74

feat: update x/sys

---

.github/workflows/lint-soft.yml
.github/workflows/lint.yml

v3 requires a manual setup-go action.

ci: update golangci-lint-action to v3

---

tutorials/commands/README.md

`errMsg(err)` -> `errMsg{err}`
Just noticed this while reading over the tutorial docs and figured I'd throw up a quick PR to address it.
Really enjoying the tooling so far, thank you for creating it!

fix: minor `tea.Cmd` tutorial syntax typo

---

examples/list-default/main.go
examples/list-fancy/main.go

This is a small improvement to the list examples to help avoid a common pitfall we've been seeing with regard to lists being too tall in alt screen views. Thanks to @mrusme for spurring the fix.

fix: use more bulletproof GetFrameSize() list examples

---

tea.go

They’re great additions and are here to stay.

docs: Program#Send, Program#Quit, and Program#Kill no longer provisional

---

README.md

Small update to the README to remove a redundant 'of'

docs: remove redundant 'of'

---

examples/exec/main.go
tea.go

This provides an interface around exec.Cmd so users can execute other things as well (i.e. any go code).
The main usecase for this that I see is for wishlist, so we can ssh into something and back to the list later instead of quitting everything :)

feat: allow to execute other things besides exec.Commands

---

examples/exec/main.go
renderer.go
screen.go
standard_renderer.go
tea.go
tty.go

`Program.ReleaseTerminal` makes Bubble Tea release the input / terminal, so users can spawn a sub-command. `Program.RestoreTerminal` sets the input reader up again and triggers a repaint.
`Exec` is provided as a `Cmd` interface, and should be the primary method for running a blocking `exec.Command` from within Bubble Tea.
Fixes #171.

add: Exec, program.ReleaseTerminal and RestoreTerminal to re-use input and terminal

---

key.go
key_test.go

This fixes a bug where the spacebar would send a `Key` with type `KeyRunes` instead of `KeySpace`. The `Runes` portion of `Key` will still contain a space after this fix.
```go
// This is what is sent when you press spacebar now
type Key struct {
Type: KeySpace,
Runes: []rune{' '},
}
```
* * *
I didn't make any changes to `readInput`. 
Manually tested `KeySpace` in addition to the tests with no issues and `KeySpace` worked as expected

fix(keys): spacebar now sends a `KeySpace`

---

key.go

https://github.com/charmbracelet/bubbles/issues/144
https://github.com/charmbracelet/bubbletea/issues/264
#264 - `tea.KeySpace` will no longer exist after this change, so their code will need to be refactored to check for " " instead

fix: fix KeySpace with textinput bubble

---

key.go
key_test.go

Treating a space differently from other runes was proving to cause more confusion that clarity. A working `KeySpace` was added in #289, however it was never released in a tagged version.

feat: obliterate type `KeySpace`

---

key.go
key_test.go

This update reverts the hasty #311 and reimplements @bashbunni's excellent #289.
After further pondering we've decided it makes the most sense to make the following small change to the message produced by the spacebar after all:
```go
// Before
Key{Type: KeyRunes, Runes: []rune{' '}}
// After!
Key{Type: KeySpace, Runes: []rune{' '}}
```
Note that the `String()` method will still return `" "` for backwards compatibility.
The reasoning for this change is that binding things to the spacebar is common, but doing so in a "safe" manner is currently a bit cumbersome. Consider the following:
```go
// For comparison
if msg.Type == tea.KeyEnter {
// Similar and straightforward
if msg.Type == tea.KeySpace {
// Urgh
if msg.Type == tea.KeyRunes && msg.String() == " " {
// Urghhhhh
if msg.Type == …
```

change(keys): spacebar sends a `KeySpace`

---

commands.go

This is always a source of confusion. Thought it would be worth to make it as clearer as possible, not sure if I got it to that point, happy to have some feedback :)

docs: improve godoc on tick and every

---

examples/exec/main.go

avoids `Error: fork/exec : no such file or directory` by using vim by default if no EDITOR is set.

docs: default to vim if no EDITOR on exec example

---

.github/workflows/build.yml

We executed tests as part of `coverage.yml` which gets executed on Linux only.

ci: run tests on all platforms

---

options_test.go

Probably just a copy/paste error.

test: fix error in custom input test

---

standard_renderer.go

I noticed that there's a race condition when resizing windows. It's happening because the main tea Program loop calls `repaint()`
https://github.com/charmbracelet/bubbletea/blob/b566614c162466b0bc5830affe289ef960fb0746/tea.go#L506
and the renderer is also setting the value of its `lastRender`:
https://github.com/charmbracelet/bubbletea/blob/b566614c162466b0bc5830affe289ef960fb0746/standard_renderer.go#L210
This can be reproduced with the [textinput example](https://github.com/charmbracelet/bubbletea/blob/master/examples/textinput/main.go). Simply run it and resize your terminal window.
Output:
```shell
$ go run -race test.go
What’s your favorite Pokémon?
> Pikachu
(esc to quit)
==================
WARNING: DATA RACE
Write at 0x00c00014c198 by main goroutine: …
```

fix: race condition on repaint

---

standard_renderer.go
tea.go

I didn't realise at the time, but the tea.Program and the renderer share
the mutex. This make the code difficult to reason about - it turns out
the program sometimes acquires the lock and then calls the
`setAltScreen` method of the renderer which in turns calls `repaint`.
That causes a deadlock as `repaint` is trying to acquire the lock too.

fix: race condition on repaint with alt screen

---

key.go
key_test.go

If tea can't keep up with reading from the input buffer, key messages might queue up and be retrieved as a batch of events. Emit them individually, so tea apps process them correctly.

fix: handle batched key msgs

---

examples/credit-card-form/main.go
examples/go.mod
examples/go.sum

Adds an example of a credit card form to `examples`.
```
Total: $21.50:
Card Number
4505 **** **** 1234
EXP     CVV
MM/YY   XXX
Continue ->
```

Example: Credit Card Input Form

---

tea.go

Fixes `Printf` typo changing it to `Println`.

Fix Printf Typo

---

examples/split-editors/main.go

Add border to focused `textarea` in split-editors example.

Add border to split-editors example

---

standard_renderer.go

chore: fix Println typo

---

README.md

Hi, thanks a lot for adding flipperzero-tea to the "Bubble Teas in the Wild"! :heart:  
I renamed the app to fztea, because I didn't like "flipperzero-tea" very much.

docs: rename flipperzero-tea to fztea

---

README.md

Added a project I've been working on to find and preview notes, to the README file.
Noted shows one of many ways you can use `viewports` from `bubbles` with `bubbletea`.
There might be enough bubbletea in the wild at this point, but here's another one.

Doc: Add `Noted` to README.md

---

.gitignore
examples/progress-download/README.md

📝 Update folder name in README to `progress-download` as
that is what generates with `go build .`
🙈 Add the files generated via README to root `.gitignore`

docs: README progress-download folder + ignore

---

examples/tabs/main.go

The [lipgloss ](https://github.com/charmbracelet/lipgloss) project has a cool example showing tabs but are static, took me a moment to figure out how to make them interactive so thought maybe someone else would benefit from an example as well. Partially addresses the issue asking for more examples with lipgloss integration: https://github.com/charmbracelet/bubbletea/issues/88 also added a gif example similar to: https://github.com/charmbracelet/bubbletea/pull/158

Example interacting with tabs using lipgloss

---

tea.go

Add [SIGTERM](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#index-SIGTERM) to signals caught so that bubbletea cleans up the screen when exiting because of that signal.
Unix utilities commonly send SIGTERM as the signal to terminate a process. Currently bubbletea doesn't catch SIGTERM and if a application receives this type of signal it will exit leaving the terminal in an unusable state. This PR causes this package to prevent this behavior and clean the terminal on exit. Examples of Unix utilities that send SIGTERM as default include `kill` and `timeout`.
To reproduce this bug run: `timeout 10 ./bubbletea-progam` 
I have tested this PR with both `timeout` and `kill`.

Catch SIGTERM so that bubbletea cleans up terminal

---

examples/debounce/main.go

docs: add debounce example

---

exec.go

The previous example was wrong and would result in the following
compiler error:
```
error (type) is not an expression
```
Just a simple typo, I've changed it to `err` to correctly reference the
function scoped variable named `err`.

docs: fix typo

---

README.md

Fixes sizing issue on GitHub mobile using `<picture>` tag.

Bubble Tea example mobile size fix

---

commands.go
examples/sequence/main.go
tea.go

Closes #413. Also note that this deprecates `Sequentially`.

feat: add `Sequence` command for running commands in order

---

README.md

Thank you for this great library!
As of [v2.23.0](https://github.com/twpayne/chezmoi/releases/tag/v2.23.0), chezmoi, a [popular dotfile manager](https://dotfiles.github.io/utilities/), uses Bubble Tea for [user interaction](https://github.com/twpayne/chezmoi/pull/2359) and [progress reporting](https://github.com/twpayne/chezmoi/pull/2369).

docs: add chezmoi to users of Bubble Tea in the wild

---

tea_test.go

Simple round-trip test that starts a model, provides fake input, waits for the model to return, and checks it printed to a buffer.
Tests:
- model start up
- event loop
- input & output buffers working

test: run model with provided input and check output

---

key.go

This can be used in e.g. textarea / textinput to enable "overwrite
mode".
cc @muesli

Support the insert key

---

examples/spinners/main.go

Sorry for the noise in `go.mod` and `go.sum`. I had to `go get github.com/charmbracelet/bubbles/spinner` in order to run the example.

fix: off-by-one error in spinner example

---

tea.go
tty.go

There's a race condition uncovered by #458, which can be triggered if the read loop doesn't finish up quickly enough, just before we spawn a child process with an exec command.
Waiting for the event loop to finish fixes the issue.

fix: wait for read-loop to finish before spawning child process

---

exec_test.go

A simple test executing `true` as a sub-process from within a `tea.Program`.

test: exec binary from within tea.Program

---

key.go
key_test.go

Fixes #466.
Also includes a removal of now-unnecessary code.
cc @muesli

fix: properly skip over unrecognized CSI sequences.

---

commands.go
tea.go

Keep `tea.Cmd` helpers in a central location instead of scattered across `tea.go`.

chore: reorganize command helpers

---

nil_renderer.go
renderer.go
screen.go
standard_renderer.go
tea.go

Fixes #236.
Fixes #116.
cc @muesli @meowgorithm

feat: support a Clear command

---

tea.go
tty.go

Ensures exclusive output access by renderer.

fix: don't access output from outside renderer

---

standard_renderer.go

Enforcing a repaint after clearing the screen prevents the line caching from interfering with the subsequent render.

fix: force repaint after clearing the screen

---

standard_renderer.go

Shortcuts switching alt mode when we're already in the desired mode.

fix: don't try to set alt screen when already in desired mode

---

key.go
key_test.go

We started supporting insert in #418, but then accidentally removed it during a rebase in #396. Oops.
:facepalm: 
cc @muesli @meowgorithm

fix(key): recover the insert key

---

tea.go
tty.go

The purpose of this change is breaking up the monstrous `StartReturningModel` into several smaller handler methods. That makes this function a bit easier to maintain and unifies the exit paths.

chore: break up Start into several, more maintainable methods

---

options.go
options_test.go
tea.go

You can now initialize a tea app without a signal handler:
p := NewProgram(model, WithoutSignalHandler())

feat: make signal handler optional

---

tea.go

Simplifies teardown and initialization of optional handlers.

chore: store handlers and simplify teardown

---

tea.go

I'm a simple man, if I see a `Close`, I call it.

fix: close input on shutdown whenever possible

---

examples/chat/main.go
examples/credit-card-form/main.go
examples/fullscreen/main.go
examples/http/main.go
examples/list-simple/main.go
examples/package-manager/main.go
examples/progress-animated/main.go
examples/progress-download/tui.go
examples/progress-static/main.go
examples/send-msg/main.go
examples/simple/main.go
examples/spinner/main.go
examples/tabs/main.go
examples/textinput/main.go
examples/views/main.go
tutorials/commands/main.go

Removes unused variables, redundant newlines, and other inconsistencies.

chore: clean up linter errors in examples

---

tea.go

Uses internal renderer method instead of the deprecated public method.

chore: don't use deprecated methods internally

---

tea.go

Entering alt screen already causes a repaint, no need to do it twice.

fix: prevent double repaint when restoring terminal

---

screen_test.go
tea.go
tty.go

- fixes mouse handling being enabled during sub commands
- fixes shutdown order: restore mouse state before alt screen

fix: restoreTerminalState resets mouse handling state

---

tea.go
tea_test.go

We can also drop the kill channel and rely on our existing context channel.

fix: kill should result in Start returning an error

---

key.go

Adds support for ctrl+(alt)+page up/down key events.
Tested in konsole, alacritty, kitty, foot, urxvt, and a few other terminals.
Fixes #369.

feat: support ctrl+page up/down keys

---

standard_renderer.go

This prevents the odd race condition where Enter- & ExitAltScreen are called concurrently.

fix: lock mutex before checking altscreen state

---

standard_renderer.go

Missed that one in the last commit.

fix: also lock mutex when accessing state read-only

---

tea.go
tea_test.go

Send should block before a `tea.Program` has been started, but result in a no-op when it has already been terminated.
Fixed the race condition on `p.ctx`.
Fixed godocs.

fix: don't block in Send after shutdown

---

tea.go

fix: don't delay messages behind a long command

---

standard_renderer.go

Drops lines from the top when the render buffer is taller than the available height.
Fixes #297.

fix: prevent renderer from overflowing available height

---

tea.go

The deferred Close call on our input reader caused the console mode to be reset twice, and the incorrect, inner mode was applied last.
Fixes #408.
Potentially fixes #563.
Fixes gum#119.
Potentially fixes gum#32.

fix: restore Windows console mode on shutdown

---

signals_unix.go
signals_windows.go
tea.go
tty.go

Based on @knz's work in #499, but slightly supersedes this change.
A little more coupling in the resize handling, but a lot less code & logic repetition.

fix: detect terminal size after exec

---

commands.go
commands_test.go
tea.go
tea_test.go

because it carry's no special meaning which should be private,
and there are use cases where its necessary to access the Batched
Messages. (I know because i have one ;)

made "batchMsg" public since it should be

---

screen_test.go
standard_renderer.go

Based on #462 and #452 by @londek, but fixes maintaining the current visibility state across altscreen state changes.
This makes the behavior consistent across terminals, some of which keep separate state for altscreen and regular buffer.
Fixes #190.

fix: maintain cursor visibility across altscreen state switch

---

options.go
tea.go
tea_test.go

WithContext lets you specify a context in which to run the Program. This is useful if you want to cancel the execution from outside. When a Program gets cancelled it will exit with an error ErrProgramKilled.

feat: tea.WithContext ProgramOption to supply a context

---

tea.go

We don't need to set the background context if an outside context was supplied.

chore: apply ProgramOptions before checking context

---

exec.go

Commands need the actual fd, not our internal output writer. Regression from 6c449e55bf0033e3d7176f48832e83d1470566d3.

fix: pass actual stdout's fd to command

---

examples/pager/main.go
examples/tui-daemon-combo/main.go

Package io/ioutil has been marked deprecated starting in Go 1.16.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>

Remove references to io/ioutil package

---

tea.go

This allows programs to re-use stdin after the tea.Program has finished.
Fixes #595.

fix: don't close stdin

---

examples/cellbuffer/main.go
examples/go.mod

This adds an example showing how to draw and animate on a pixel-like grid. Note that this cellbuffer implementation does not support double-width runes.
https://user-images.githubusercontent.com/25087/185721406-8d1b35e1-f524-4908-a8b0-2711aa8e9f30.mp4

docs(examples): add cellbuffer + harmonica example

---

tea.go

fix: Check msg cmd is not nil before invoking

---

examples/go.sum
examples/sequence/main.go
go.mod
go.sum
tea.go
tea_test.go
tutorials/go.sum

#415 added support for `tea.Sequence`. This adds support for `tea.Batch` cmd in the `tea.Sequence` cmd.
Fixes #582

feat: `sequence` support `BatchMsg`

---

tea.go

This PR fixes an issue where a user may provide a nil input via `tea.WithInput(nil)`.  This option method does not check if the input is nil and sets the `withCustomInput` attribute with a nil input. This logic is sound since a Tea program may not necessarily want to handle any inputs from users (such as those in non-TTY environments).
However, a nil pointer exception is thrown during `tea.Run` because the `cancelReader` is always invoked after the main renderer.  Its instantiation is variable and dependent on whether an input is provided. To mitigate against this, this PR checks if `cancelReader` is non-nil.

fix: Check if program cancelReader is is nil before invoking

---

standard_renderer.go

Ensure the tea renderer can be stopped and restarted more than once.

fix: renderer only stops once

---

standard_renderer.go
tea.go

Stops the renderer before starting a child process, which prevents the repaint race condition that writes to non-altscreen.

fix: stop renderer before launching a child process.

---

README.md

I have recently created an open-source tool for simple WireGuard configuration management. 
bubbletea (as well as lipgloss) is a delight to use. I would be happy if it is possible to mention my project on the bubbletea page. 
Thank you.

Add WG Commander to README.md

---

logging.go

Allows to log to file with custom loggers, provided they implement SetOutput and SetPrefix.
This would allow to do something like:
```go
// ...
import "github.com/charmbracelet/log"
// ...
// ...
tea.LogToFileWith("foo.log", "prefix", log.Default())
// ...
```

feat: LogToFileWith

---

examples/prevent-quit/main.go
options.go
options_test.go
tea.go
tea_test.go

`WithFilter` lets you supply an event filter that will be invoked before Bubble Tea processes a `tea.Msg`. The event filter can return any `tea.Msg` which will then get handled by Bubble Tea instead of the original event. If the event filter returns `nil`, the event will be ignored and Bubble Tea will not process it.
As an example, this could be used to prevent a program from shutting down if there are unsaved changes.
Based on the fantastic work by @aschey and supersedes https://github.com/charmbracelet/bubbletea/pull/521.
Might make #114 more relevant.
Resolves https://github.com/charmbracelet/bubbletea/issues/472.

feat: add generic event filter

---

options.go

If the passed io.Writer is a termenv.Output, use it instead of creating a new termenv.Output.

fix(output): reuse termenv output

---

tea.go

wait for the underlying context to finish.
extract from #352

feat: tea.Wait

---

options.go
options_test.go

Extracted from #352
Signed-off-by: Carlos Alexandro Becker <caarlos0@users.noreply.github.com>

feat: allow to disable signals

---

options.go
options_test.go
tea.go

Just some internal housekeeping: basically `WithCustomInput` and `WithInputTTY` can not longer both exist in `startupOptions` internally. When both are passed as `ProgramOption`s the last one wins.

chore: make input options mutually exclusive

---

standard_renderer.go

fix: stop renderer before acquiring renderer mutex

---

options.go
standard_renderer.go
tea.go

Solves issue #577 
Added the ~`WithMaxFPS`~ `WithFPS` option to bubbletea program struct, if it is set with a non 0 value it will set the maximum interval at which the view is updated, if it is not set or set to 0, the interval will be the `defaultFramerate` constant.

(feat): Add option to set max FPS

---

key.go
key_sequences.go
key_test.go
mouse.go
mouse_test.go

This PR contains only the input simplification part of #511.
cc @muesli

fix(key),test: simplify the input analysis code

---

key.go
key_test.go
tty.go

First commit from #568.
This is the control flow change discussed in https://github.com/charmbracelet/bubbletea/pull/511#issuecomment-1287061948
cc @muesli

fix(key): invert the control loop

---

examples/credit-card-form/main.go

Fixes Index out of range error in examples/credit-card-form when credit card number(CCN) is not provided.
To reproduce:
- Run examples/credit-card-form/main.go
- Do not type anything in "Card number"
- Press UP or DOWN keys on your keboard (or press TAB several times)
_ccnValidator_ will trigger and will attempt to read a symbol which is located at _len("")-1_, that will cause Index out of range error (because CCN is empty).

fix: Index out of range in examples/credit-card-form when ccn is empty

---

tty.go
tty_unix.go

Just soft linter stuff, though I could see this being helpful in development.

chore(lint): wrap various TTY-related errors

---

examples/autocomplete/main.go

Two small adjustments here:
* Change placeholder from `bubbletea` (as it's not actually completable)
* Add autocomplete keys to the help text

chore: minor UX edits to autocomplete example

---

key.go

I also mentioned it in #594 ! You have to fix the mouseEventLen here otherwise it will throw after each detected sgr event random keyRunes Events with left over chars. Bad for focused input fields and so on. SGR events dont have like X10 Events a fixed length of 6.

fix: key.go missing sgr event len calculation

---

key.go
key_test.go

Fixes #502.
First two commits from #568 and #569. 
Split away from #511 as discussed in https://github.com/charmbracelet/bubbletea/pull/511#issuecomment-1287061948
cc @muesli

fix(key): support very long buffered input

---

options.go
options_test.go
tea.go

multiple goroutines can try  to `ReleaseTerminal` (and/or `RestoreTerminal`) at the same time, causing a data race.

fix: race changing ignoreSignals

---

examples/go.mod
examples/go.sum

Just a regular ol’ dep update for the examples.
Closes #882.

chore(examples): bump the bubbles dep in the examples to v0.17.0

---

README.md

adding [redis_tui](https://github.com/mat2cc/redis_tui) to bubbletea in the wild

docs: adding redis_tui to readme

---

examples/fullscreen/main.go

The docs say you shouldn't do this - https://github.com/charmbracelet/bubbletea/blob/8f3464a75600e991bbce22229d6e5b99975416f0/screen.go#L29 - and it works just fine with it removed.
Removing it will make sure that people who are new don't go down the wrong path looking at this example.

chore(docs): remove the tea.EnterAltScreen from Init

---

examples/simple/testdata/TestApp.golden
key.go
key_sequences.go
key_test.go
nil_renderer.go
options.go
options_test.go
renderer.go
screen.go
screen_test.go
standard_renderer.go
tea.go
tty.go

First 3 commits from #568, #569 and #570.
Partial fix to #404
This introduces support for input via bracketed paste, where escape
characters in the pasted input are not interpreted.
Pasted input are marked as a special field in the KeyMsg.
This is because pasted input may need sanitation in individual widgets.
cc @maaslalani @muesli

feat: bracketed paste

---

signals_unix.go
tty_unix.go

Hello Charm team,
I work on the Go compiler for z/OS and would love to have bubbletea programs work out of the box on our platform.
There are two dependencies that also need z/OS support for perfect out of the box support, but I've opened PRs for both of them ([termenv](https://github.com/muesli/termenv/pull/165) & [clipboard](https://github.com/muesli/termenv/pull/165))
As for bubbletea, the build and all tests are passing on z/OS after the addition of these tags.

Add support for z/OS

---

standard_renderer.go

When logging something into the scrollback history of the standard renderer, the current approach temporarially increases the size of the UI by the number of logged messages. This has 2 issues:
- log lines are truncated according to the current width of the terminal UI. This truncation behaviour is desireable when writing into the TUI's controlled space, but is not desireable when Printf()ing messages into the scrollback, since the contents of the logged line will be truncated with no way to recover the history.
- User code pre-wrapping messages they want to print to the scrollback don't behave the way that you would want/expect log lines in a terminal to behave:
- Resizing the terminal emulator does not reflow the lines to the new terminal's width
- Manual wrapping breaks most terminal …

Support multiline tea.Println() messages

---

examples/list-fancy/main.go

As described by the godocs, instead of calling `tea.EnterAltScreen`  in the `init` method, the correct way is to initialize the program with the `tea.WithAltScreen`

chore: start program with alt screen instead of init

---

examples/go.mod
examples/go.sum
go.mod
go.sum
inputreader_other.go
inputreader_windows.go
key.go
key_other.go
key_test.go
key_windows.go
tty.go
tutorials/go.mod
tutorials/go.sum

This adds support to the Windows Console Input Buffer API which access the console API directly without the need for virtual terminal input (i.e. the current mode that emulates unix inputs). Since this uses the console input api, we can finally read window size events.
This is mearly based on the awesome work of @erikgeiser in #140.
Fixes: https://github.com/charmbracelet/bubbletea/issues/538
Fixes: https://github.com/charmbracelet/bubbletea/issues/121

feat: support windows console input buffer

---

README.md

1 line change to add [puffin](https://github.com/siddhantac/puffin) to `Bubbletea in the wild` section of the Readme.
_if there is a different way to do this, please let me know and I will close the PR :)_

Add puffin to 'Bubbletea in the wild'

---

examples/file-picker/main.go

Fixes #852 
The cursor has trouble mapping to the correct location when using stderr. Using stdout is more reliable, and this example isn't taking advantage of stderr in any meaningful way over stdout, so it's probably better to show people a more common example.

fix(examples): run filepicker on stdout (versus stderr)

---

commands.go

Minimal fix that returns the single command instead of wrapping it in a `Batch`

chore: optimize batches with one item

---

tea.go

Not really much of a danger, but probably helpful to make the `handler` type name more explicit.

chore: don't shadow 'handler' type

---

examples/go.mod
examples/go.sum
go.mod
go.sum
tea.go
tty.go
tty_unix.go
tty_windows.go
tutorials/go.mod
tutorials/go.sum

Replace mattn/isatty and containerd/console with golang.org/x/term.
This mostly affects Windows. On Windows, unlike Unix, the console (TTY) has different handles for input/output. Using the Console API, we need to enable VT input on the input handle (CONIN) and VT processing on the output handle (CONOUT). Doing so enables processing VT sequences on Windows i.e. ANSI colors, mouse sequences, cursor movements, etc.
We already handle enabling VT processing for the program output using Termenv `EnableVirtualTerminalProcessing`. For the input side, we enable VT input right before setting the console to raw.
By doing this, we can drop both containerd/console and mattn/isatty.

feat: reduce console/term dependencies

---

README.md

Hi, 
I added a link to my chatgpt project in the Bubble Tea in the Wild section of the README.
This is how it looks:

docs: add a link to chatgpt-cli

---

README.md

Hello, Bubbletea team. Thank you for your great library 🎉
I created a Bubbletea project for managing Docker containers that look like Docker Desktop. I added the link in the Wild section of the README. 
Preview of my Bubbletea project:

docs: add link to laboon project

---

README.md

Hello! [My CHIP-8 project](https://github.com/braheezy/chip-8) now renders as a TUI using BubbleTea. I didn't any similar projects in the README so I thought it'd be neat to add mine. Thanks in advance!

docs: Add CHIP-8 to projects in the wild

---

README.md

Added 3 projects to the "In the Wild" section:
* [cueitup](https://github.com/dhth/cueitup): inspect messages in an AWS SQS queue in a simple and deliberate manner
* [kplay](https://github.com/dhth/kplay): inspect messages in a kafka topic in a simple and deliberate manner
* [outtasync](https://github.com/dhth/outtasync): identify cloudformation stacks that are out of sync with their template files
PS. Thanks for making bubbletea!

docs(README): add cueitup, kplay, outtasync to "in the wild"

---

README.md

I ran into a bit of difficulty trying to connect the VS Code debugger to the process spawned by `dlv debug`. I eventually figured out that delve defaults to its legacy protocol (version 1) by default which was causing compatibility issues with VS Code's Go integration. Delve's docs recommend using version 2 for all new development, so I think it makes sense to add that to the docs so people trying to integrate with IDEs hopefully don't run into the same compatibility issues. Also added a note about supplying the port so these commands can integrate with IDEs and shell scripts without having to figure out the port each time.

docs: update delve information

---

README.md

Added 2 projects to "In the Wild" section:
- [punchout](https://github.com/dhth/punchout): takes the suck out of logging time on JIRA
- [schemas](https://github.com/dhth/schemas): lets you inspect postgres schemas in the terminal

docs(readme): add punchout and schemas to 'in the wild'

---

README.md

Similarly to the other two chatgpt related entries in the list tgpt (https://github.com/aandrew-me/tgpt.git) is a commandline frontend, except it has >1500 stars.
I have been daily driving it for weeks now and with its Bubbletea interface its a nice and smooth experience.
The description I inserted to the README is an exact copy of its official github description.

chore(README): add tgpt to 'in the wild'

---

key_windows.go

Hey :wave: 
This PR adds support for more `ctrl` and `shift` modifiers on windows using the new coninput api.
closes [#161](https://github.com/charmbracelet/huh/issues/161)

fix: support more shift and ctrl modifiers on windows

---

commands.go

Stop the timers and drain them.
I got a situation in which this was causing a bubbletea app to use **A LOT** of ram.
Per my understanding, some timed commands were being fired twice sometimes... on most cases this might not be perceptible, but in this particular case, each of these commands generated another message, and the program went on double firing those too.

fix: stop and drain timers

---

examples/simple/testdata/TestApp.golden
screen_test.go
standard_renderer.go

We need to reset the cursor position on the first line before rendering. Otherwise, it might mess up the first line being rendered.
Supersedes: https://github.com/charmbracelet/bubbletea/pull/1006
Fixes: https://github.com/charmbracelet/bubbletea/issues/1000
Fixes: 46241068daed (feat: reduce console/term dependencies (#897))

fix: renderer: reset the cursor on the first line

---

screen.go
tea.go

Using program commands like p.EnableMouseCellMotion and p.SetWindowTitle _before_ the program starts can panic the application since `renderer` hasn't been initialized yet. Use program options to enable and set these options if `renderer` is not initialized.
Fixes: https://github.com/charmbracelet/bubbletea/issues/1029

fix: program renderer commands

---

key_windows.go

Before, when emitting a key event containing a control sequence, the character would also be included.
The `textinput` bubble would see this as user input and sanitize it, converting `\r` to a space and appending it.
Even though this fixes the issue, the real problem lies in the fact that text input is accepted before (all) key binds are processed, presumably because it is assumed that control sequences don't contain any characters (which is the case on Unix, and with this PR now also on Windows). ~~This should be looked into in a separate issue in the `huh` repository.~~ https://github.com/charmbracelet/huh/pull/284
Thanks @robotastronaut for sharing their research in the Charm Discord server and for the [initial fix](https://github.com/charmbracelet/bubbletea/commit/ae18b80676e60b3a5a1eb …

fix(windows): Fix coninput not handling control sequences

---

.github/workflows/release.yml
.goreleaser.yml

This will publish and announce releases on tag push.

feat(ci): use goreleaser for releases

---

examples/package-manager/main.go

I fixed 3 bugs in the package-manager example (they are easier to spot when working with a small list of 4, for example):
1. The total packages count.
2. The progress bar percentage.
3. The final installed package in the output.

fix(examples): Fix bugs in package-manager

---

examples/altscreen-toggle/main.go
examples/go.mod
examples/go.sum
examples/simple/main.go
examples/simple/testdata/TestApp.golden
examples/suspend/main.go
exec.go
tea.go
tty.go
tty_unix.go
tty_windows.go

closes #497
closes #1053
based on @knz's implementation. thanks ❤️

feat: allow to suspend bubbletea programs

---

examples/simple/testdata/TestApp.golden
screen_test.go
standard_renderer.go

We need to reset the cursor position to the beginning of the line when the program stops or exit.
Related: https://github.com/charmbracelet/gum/issues/607

fix: reset cursor position on renderer exit

---

commands.go
tea.go

Fixes: https://github.com/charmbracelet/bubbletea/issues/987#issuecomment-2068452658

feat: add a cmd to request window size

---

examples/window-size/main.go
tea.go

We need to run checkResize in a goroutine, otherwise, it will block.
Related: https://github.com/charmbracelet/bubbletea/pull/988#issuecomment-2231811332
Fixes: 7d708384a105 (feat: add a cmd to request window size (#988))

fix: query window-size in a goroutine

---

options.go
tea.go

This adds the option to provide a custom set of environment variables to use in the Bubble Tea program. When running Bubble Tea in a remote session such as SSH, we need to be able to pass the SSH session's environment variables rather than the server ones.
```go
// Add the TERM from the SSH session to the environment
var sess ssh.Session // from the github.com/charmbracelet/ssh package
pty, _, _ := sess.Pty()
environ := append(sess.Environ(), "TERM="+pty.Term)
p := tea.NewProgram(model{}, tea.WithEnvironmen(environ))
```
Now, the Bubble Tea program running for a remote session can determine the appropriate color profile from the session's environment variables instead of the _server's_ environment variables.
In most cases you'll only need this feature when using Bubble Tea in remote …

feat: set the program environment variables

---

go.mod
go.sum
key_test.go
kitty.go
options.go
screen_test.go
tea.go
tty.go

This adds the necessary options to enable/disable the kitty keyboard protocol.
Needs: https://github.com/charmbracelet/bubbletea/pull/1080
Fixes: https://github.com/charmbracelet/bubbletea/issues/869

feat: add kitty keyboard options and settings

---

commands.go
examples/go.mod
examples/go.sum
examples/print-key/main.go
go.mod
go.sum
key_test.go
kitty.go
options.go
tea.go
tty.go
xterm.go

This is an alternative protocol to Kitty. They can go hand-in-hand and
it's up to the terminal to report the encoded sequence.

feat: support xterm modifyOtherKeys keyboard protocol

---

da1.go
parse.go
tea.go
xterm.go

This adds support for XTVERSION and DA1 querying.
XTVERSION responds with the version of the terminal (not supported by all terminals)
DA1 responds with some of the terminal capabilities

feat: query the terminal version string and primary device attrs

---

color.go
examples/set-terminal-color/main.go
screen_test.go
tea.go

This adds the ability to read and set terminal background, foreground, and cursor color.
Supersedes: https://github.com/charmbracelet/bubbletea/pull/567
Fixes: https://github.com/charmbracelet/bubbletea/issues/207

feat: query and set terminal background, foreground, and cursor colors

---

clipboard.go
parse.go
screen_test.go
tea.go

This adds support to setting the system and primary (X11 & Wayland) clipboards using OSC52. This makes the clipboard commands work even on remote session such as SSH.
While this doesn't work on all terminals, most modern terminals support OSC52 including Alacritty, Kitty, Xterm.JS, etc. For terminals, that don't support OSC52, application developers should consider using a Golang clipboard library like https://github.com/atotto/clipboard.
OSC52 support can be detected if the terminal responds to a `ReadClipboard` command.
Fixes: https://github.com/charmbracelet/bubbletea/issues/982

feat: support setting and querying the terminal clipboard using OSC52

---

examples/simple/testdata/TestApp.golden
nil_renderer.go
nil_renderer_test.go
options.go
options_test.go
renderer.go
screen.go
screen_test.go
standard_renderer.go
tea.go
tty.go

This adds the ability to use a custom renderer using a modified version of the existing `renderer` interface. This also keeps track of enabled capabilities and ensure they are turned off on program exit. It only turns off enabled capabilities rather.
The new API looks like:
```go
// Renderer is the interface for Bubble Tea renderers.
type Renderer interface {
// Close closes the renderer and flushes any remaining data.
Close() error
// Render renders a frame to the output.
Render(string) error
// SetOutput sets the output for the renderer.
SetOutput(io.Writer)
// Flush flushes the renderer's buffer to the output.
Flush() error
// InsertAbove inserts lines above the current frame. This only works in
// inline mode.
InsertAbove(string) error
// Resize sets the size of the terminal.
Resize(w …
```

feat: expose the renderer interface

---

exec_test.go
tea.go
tea_test.go

This is a useful breaking change that makes `Init()` return the model used in the program. This makes it possible to do creative things in programs with multiple models where the program needs to change the main model.

feat!: make Init return the model

---

tty.go

Otherwise, a raw terminal will mess up the output. This is because a raw terminal disables termios OPOST mode which converts newlines to `\r\n` to reset the cursor to the beginning of the screen on new lines.
CC/ @cwarden
Fixes: https://github.com/charmbracelet/bubbletea/issues/1069

fix: we don't initialize the terminal when using a nilRenderer

---

.github/workflows/build.yml

Use charmbracelet/meta build workflow to build and test bubbletea and its examples.
Needs: https://github.com/charmbracelet/meta/pull/158
Needs: https://github.com/charmbracelet/meta/pull/159
Needs: https://github.com/charmbracelet/meta/pull/160

feat(ci): use meta build workflow

---

key.go
kitty.go
options.go
parse.go
screen_test.go
tea.go
win32input.go
xterm.go

This exports the following modes:
- Kitty keyboard commands and options
- Xterm modifyOtherKeys commands and options
- Win32Input commands and options

(v2) Export different input mode commands and messages

---

README.md

Preview: https://github.com/charmbracelet/bubbletea/blob/in-the-wild/README.md#bubble-tea-in-the-wild

docs(featured): clean up in the wild list

---

tea.go

We should recover from panics within a cmd. Currently, Bubble Tea only recovers from panics within the eventLoop. This makes it so that it also recovers from panics within cmd go routines.
Supersedes: https://github.com/charmbracelet/bubbletea/pull/846
Fixes: https://github.com/charmbracelet/bubbletea/issues/234

fix: recover from panics within cmds

---

examples/pager/main.go
options.go
standard_renderer.go

These revisions deprecate the high performance rendering set of commands:
* `SyncScrollArea()`
* `ClearScrollArea()`
* `ScrollUp()`
* `ScrollDown()`
Performance rendering is very hard to implement, goes against Bubble Tea's Elm Architecture design patterns, and is very limited in that it can _only_ operate on the entire width of the terminal at once (so it won't work in, say, a viewport that spans half of the terminal width).
We’re also deprecating `WithANSICompressor()` as it has very noticeable performance costs which we believe outweigh the bandwidth benefits otherwise provided.

Deprecate high performance rendering feature and ANSI compressor

---

examples/go.mod
examples/go.sum
exec.go
options.go
options_test.go
standard_renderer.go
sync.go
tea.go
tty_unix.go
tty_windows.go

This implements a wrapper around p.output that locks the output on every write. We also need to redefine `channelHandlers` to be thread-safe since `p.Kill()` can be called from a different thread while the program is running.

fix: use safeWriter to guard writing to output

---

key_test.go
kitty.go
parse.go

Kitty Keyboard protocol extension also applies to legacy CSI A, CSI B, and others, and CSI ~

fix: handle Kitty keyboard protocol extensions to legacy sequences

---

go.mod

We also need to do the same with bubbles. That's why the examples are failing

feat!: v2: update module path to github.com/charmbracelet/bubbletea/v2

---

options.go
tea.go

Right now, we only have one experimental feature to use the new cell buffer as a default renderer. Use `TEA_EXPERIMENTAL=cellbuf` environment variable to enable the use of the cell buffer as the default renderer.

(v2) feat: add experimental features

---

cursor.go
examples/cursor-style/main.go
tea.go

This commit adds support for changing the cursor style. The new `SetCursorStyle` command can be used to change the cursor style to one of the following:
- `CursorBlock`
- `CursorUnderline`
- `CursorBar`

feat: support changing the cursor style

---

examples/simple/testdata/TestApp.golden
options.go
screen_test.go
tea.go

This commit changes the behavior of grapheme clustering to be opt-in instead of opt-out. This is because some terminals like Apple Terminal don't support DECRQM and DECRPM, which are required for querying and setting the grapheme clustering state.
Apple Terminal, instead, replies with a `p` character when querying the grapheme clustering state, which is not a valid response and breaks the program output.
Notice the `p` in the first line

(v2) fix: make grapheme clustering opt-in

---

cancelreader_windows.go

Before initializing the input reader, we need to ensure that the console input buffer is empty, otherwise, we can get dangling events from previous sessions.
Fixes: https://github.com/charmbracelet/bubbletea/issues/1167
Supersedes: https://github.com/charmbracelet/bubbletea/pull/1180
CC/ @denish3436

(v2) fix: windows: ensure the input buffer is empty

---

.github/workflows/lint-sync.yml

This adds a new workflow that runs manually or every week to sync the linter configuration from the meta repo. It will simply open a PR with the changes, which can be reviewed and merged as needed.

feat(ci): use meta lint-sync workflow to sync linter config

---

cell_renderer.go
cursor.go
examples/go.mod
examples/go.sum
key_test.go
parse.go

You can now set the cursor position in Bubble Tea cell renderer.
```go
// func SetCursorPosition(x, y int) Cmd
// In your Update
func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
// ...
return m, tea.SetCursorPosition(0, 3) // set the cursor position to the beginning of the 4th line
}
```
Fixes: https://github.com/charmbracelet/bubbletea/issues/918
Fixes: https://github.com/charmbracelet/bubbletea/issues/874

(v2) feat: support setting cursor position

---

examples/go.mod
examples/go.sum
standard_renderer.go

fixes #1232
To fix the bug described in the issue, we can simply store the currently rendered lines and use them for comparison in the upcoming flush operation.

fix: incorrect line skipping in renderer flush

---

standard_renderer.go

When exiting alternate screen mode, the cursor was not properly adjusted, which caused terminal content to be either overwritten (if the current line count was greater than before entering alt screen) or leftover lines to remain at the top (if the current line count was smaller). To fix this, we save the number of lines rendered before entering alternate screen mode. When exiting, we compare the current line count with the saved value and adjust the cursor position accordingly, ensuring correct positioning and preventing both overwriting and leftover lines.
fixes #1013

fix: cursor position adjustment after exiting alt screen

---

screen_test.go
standard_renderer.go

We need to keep a separate count of lines rendered in the alt screen and
inline mode. This is because when we enter alt screen mode, the cursor
position is saved, and the alt screen is cleared. Now when we exit the
alt screen mode, the cursor position is restored so we don't need to
move the cursor to the beginning of the section that we rendered.
To fix this, we keep a separate count of lines rendered in the alt screen
mode and inline mode.
Related: https://github.com/charmbracelet/bubbletea/issues/1013
Fixes: https://github.com/charmbracelet/bubbletea/pull/1241
Fixes: https://github.com/charmbracelet/bubbletea/issues/1248
CC/ @unitsvc @semihbkgr

fix: renderer: keep a separate count of lines rendered in the alt screen 

---

examples/suspend/main.go
options.go
tea.go

This PR introduces `Interrupt()`, `InterruptMsg{}`, and `ErrInterrupted`.
Users can still handle "ctrl+c" as before, but instead of return `tea.Quit`, they can return `tea.Interrupt`.
Later on, they can check if `errors.Is(err, tea.ErrInterrupted)`, and `os.Exit(130)` if they want to exit with a different code.

feat(SIGINT): better handle interrupts

---

standard_renderer.go

I think it was overlooked in #1251
@aymanbagabas

fix: getting last rendered line counts including alt screen lines

---

examples/glamour/main.go

This fixes markdown rendering in the Glamour example. It depends on https://github.com/charmbracelet/lipgloss/pull/411.

docs(examples): fix glamour example

---

environ.go
tea.go

Send the environment variables used by the program to the program when it starts. This is done by sending an `EnvMsg` message to the program. Programs that need to access the environment variables can use this message type to get the values of the environment variables.
This is useful when programs targeting remote sessions need to access environment variables that are set by the user or the shell.
Example:
```go
type model struct {
term string
}
func (m model) Init() (tea.Model, tea.Cmd) {
return m, nil
}
func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
switch msg := msg.(type) {
case tea.EnvMsg:
m.term = msg.Getenv("TERM")
}
return m, nil
}
func (m model) View() string {
return "We're running $TERM=" + m.term
}
```

(v2) feat: add environ type and EnvMsg message

---

README.md

This PR updates outdated references in the README.md file that pointed to the `master` branch, replacing them with references to the `main` branch. This ensures the documentation reflects the current branch naming convention and avoids confusion for new users.

Update documentation references from 'master' to 'main' branch

---

examples/space/main.go

This is a simple example that uses Lip Gloss and Bubble Tea to render a moving color gradient. Ported from @orhun's [stdout vs stderr post](https://blog.orhun.dev/stdout-vs-stderr/#measuring-fps) and https://github.com/orhun/rust-stdout-vs-stderr/blob/main/src/stdout-vs-stderr.rs

(v2) feat(examples): add space example to measure fps and performance

---

options.go
screen.go

This revision depreciates the following `ProgramOption`s in favor of `Cmd`s. All of these will be removed in `v2`.
* `WithAltScreen` (use [`EnterAltScreen`](https://pkg.go.dev/github.com/charmbracelet/bubbletea#EnterAltScreen))
* `WithoutBracketedPaste` (use [`DisableBracketedPaste`](https://pkg.go.dev/github.com/charmbracelet/bubbletea#DisableBracketedPaste))
* `WithMouseCellMotion` (use [`EnableMouseCellMotion`](https://pkg.go.dev/github.com/charmbracelet/bubbletea#EnableMouseCellMotion))
* `WithMouseAllMotion` (use [`EnableMouseAllMotion`](https://pkg.go.dev/github.com/charmbracelet/bubbletea#EnableMouseAllMotion))
* `WithReportFocus` (use [`EnableReportFocus`](https://pkg.go.dev/github.com/charmbracelet/bubbletea#EnableReportFocus))
For equivalent functionality, just return the …

chore: deprecate some StartupOptions in favor of Cmds

---

standard_renderer.go
tea.go

Readd the standard line-based renderer behind `TEA_STANDARD_RENDERER=1` environment variable flag. This uses `colorprofile.Writer` to downsample colors.

(v2) feat: renderer: readd standard renderer

---

key_windows.go

On Windows, some keyboard layouts have an AltGr button that's similar to the Mac options button and can be used to send characters. This PR respects the AltGr button and treat its characters as bubbletea key runes.
Fixes: https://github.com/charmbracelet/bubbletea/issues/1126

fix: windows: AltGr maps to LEFT_CTRL+RIGHT_ALT

---

screen.go

Just following https://github.com/charmbracelet/bubbletea/pull/1307 :)
If `With` program options are now deprecated, you should not encourage to use them instead of commands.

Remove irrelevant option comments

---

options.go
screen_test.go

This adds a new option to set the initial window size of the terminal window. This is useful in testing and required for teatest/v2 after the changes in the renderer. The cell-based cursed renderer heavily relies on the terminal size, and it's important to have a way to set the size manually for tests to run in a non-interactive environment.

feat: add WithWindowSize option to set the initial window size

---

examples/simple/testdata/TestApp.golden
standard_renderer.go

Using cud1 (`\x1b[B`) won't scroll the terminal if the cursor is already at the bottom of the screen. Instead, use a newline character to move the cursor down and scroll the terminal if necessary.
Fixes: https://github.com/charmbracelet/bubbletea/issues/1322

fix: renderer: use newline instead of cud1 to move cursor down

---

exec.go
tea.go
tty.go

The cursed renderer moves the cursor between renders, which can cause issues when the terminal is released and restored. For instance, when we exec a command using tea.Exec, we want the cursor position to remain the same after the command finishes and goes back to the same position as before the command was executed.
With tea.Suspend on the other hand, we want to make sure we reset the cursor position because the program stops executing and is put to suspend. Resuming the program again initializes the renderer and its cursor position again from scratch as if it was a new program.
This wasn't an issue for the standard renderer because we always put the cursor at the lower left corner of the screen. Releasing and restoring the program wasn't an issue because the cursor was always at the …

fix: reset renderer and cursor when releasing terminal

---

.github/workflows/coverage.yml

This commit moves the coverage reporting from goveralls to codecov and fixes broken coverage CI.

feat(ci): move from goveralls to codecov

---

cursor.go
examples/tui-daemon-combo/main.go
options.go
options_test.go
tea.go
tty.go

This change separates the viw from the main model by introducing new interfaces `ViewModel` and `CursorModel`. The `ViewModel` interface provides a view method that returns the string to render, while the `CursorModel` interface provides a view method that returns the string to render and the cursor position.
If a program does not implement a view interface, the program won't render anything. This removes the need for the `WithoutRenderer` option.

feat: separate view in its own interface

---

options.go
options_test.go
tea.go
tea_test.go

Here's all my deadlock/race condition/error handling fixes stacked and combined for review convenience and CI-testing.
Includes:
- #1372 
- #1373 
- #1375 
Many thanks for your efforts and bearing with my pull requests. 💯 🚀 
For a **v2-targeted version** of these fixes see:
- #1388

(v1-0/3) tea.go: all fixes combined (for convenience/CI)

---

tea.go
tea_test.go

fixes #1370
closes #1292 
context cancellation causes immediate exit of channel receiving routine _handleCommands_
select statement wrap prevents deadlocks on _eventLoop_ sends to stale channel and ensures routine exit

(v1-1/3) tea.go: fix deadlock on context cancellation

---

options.go
options_test.go
tea.go
tea_test.go

This PR contains the v2-targeted and v2-applicable portions of the following v1-targeted fixes:
- #1376 
- #1372 
- #1373 
- #1375
Meaning it fixes all above issues in v2, the bugs that are not already resolved otherwise in v2.
Issues are related to deadlocks and wrongful nil returns on error, PR adds a couple of tests as well.

(v2) tea.go: deadlock/error return fixes, additional tests (targeted at v2)

---

key_windows.go

We ignore function keys on Windows. This was introduced after we switched to the Windows API.
This commit simply adds function keys from F1 to F20.
Fixes: https://github.com/charmbracelet/bubbletea/issues/1404

fix(key): windows: recognize function keys on Windows

---

examples/textinput/main.go

This adds virtual cursor support to the `textinput` example.
cc: @kujtimiihoxha

docs(examples/textinput): support virtual cursor

---

tea.go

When Bubble Tea panics, it is really useful to have a trace file that contains the panic message and the stack trace. This does that exactly.

feat: create a panic trace file

---

screen.go

Thanks for the wonderful documentation. That was a pleasure to read on the subway. Just wanted to point out there's an error in the DisableBracketedPaste comment. I've reviewed all the PRs and confirmed there are no duplicates. Maybe?

chore: correct DisableBracketedPaste behavior in comment

---

commands.go
commands_test.go

This change makes `Sequence` behave like `Batch` in how it handles `nil` entries, preventing a possible infinite loop.
I stumbled across this discrepancy when I noticed a bubbletea program I had written had CPU usage over 100% all the time, when I would expect it near zero as a CLI simply waiting for input.
I created a [simplified repro](https://github.com/jdhenke/repro-bubbletea-sequence-bug/blob/main/main.go), and noticed that swapping in `tea.Batch` for `tea.Sequence` fixed the CPU usage, which was nice, but it seems like either one _should_ work.
Digging in, it looks like `Batch` already had logic to handle all nils in #217 and more recently to return the only non-nil entry directly if possible in #875. This change reuses the same logic (and tests) for `Sequence` as well now, which …

Compact sequences like batches
