charmbracelet/bubbletea

tutorials/basics/README.md

love this library. Looking forward to working with it more 👍

fix: small typo in url

---

README.md

Fix return value of Init() in README

---

key.go

This PR adds support for input method editors that insert more than one character at a time. Note that the textinput component in Bubbles will also require a minor update as well.
Closes #20.

Support multi-character input (i.e. Chinese and Japanese IME)

---

mouse.go
mouse_test.go

Hi! I've added some tests for `mouse.go` and rewrote `parseX10MouseEvent()`.
Maybe you will find them useful. :)

Add tests for `mouse.go`

---

logging.go

Dead simple, but now it works as expected, lol
Also, sorry for multiple PRs, fix simple errors like this is way more easy in github website, instead commiting via git.
If you don't allow it, i'll sending PRs from git command.

Fix: Log prefix in files now actually adding

---

renderer.go
signals_windows.go
tea.go
tty_unix.go

Found a couple of them in one file, reviewed all files to make sure there aren't more.

Fixed a couple of typos

---

README.md

Awesome project! I enjoyed using it to build ticker and look forward to seeing the ecosystem grow over time

docs: Added ticker to list of things built with Bubble Tea

---

examples/realtime/main.go

This was extracted from the discussion in #25.

Add example illustrating how to send messages via channels in realtime

---

.gitignore
examples/altscreen-toggle/main.go
examples/fullscreen/main.go
tea.go

Add commands for toggling the altscreen

---

README.md

Hey, Thank you for the awesome work of this TUI framework! 
I love :heart: it so much, and I recently developed a tool called [httpit](https://github.com/gonetx/httpit) which uses bubbletea as its TUI.
I'm wondering if I can put this project in `Bubble Tea in the Wild ` section?

Add item for Bubble Tea in the Wild section

---

tea.go

We can't really handle this, make it clear that's intentional.

Omit unhandled error

---

examples/pager/main.go
examples/realtime/main.go
examples/simple/main.go
examples/views/main.go

Fix various typos in examples

---

examples/spinners/main.go

Fix ineffectual assignment in spinner example

---

standard_renderer.go

Ran into race condition [here](https://github.com/gonetx/httpit/runs/2267718515?check_suite_focus=true), and this pr can fix it.

Add lock for updating width and height

---

examples/paginator/main.go

Hi, I'm couldn't found an paginator example so I created one \o/.

Add paginator example

---

examples/countdown/main.go
examples/fullscreen/main.go
examples/glamour/main.go
examples/http/main.go
examples/mouse/main.go
examples/pager/main.go
examples/paginator/main.go
examples/pipe/main.go
examples/progress/main.go
examples/result/main.go
examples/simple/main.go
examples/spinner/main.go
examples/spinners/main.go
examples/textinput/main.go
examples/textinputs/main.go

This PR contains some general tidying up of the examples.

Clean up and normalize examples

---

README.md

This PR adds [fm](https://github.com/knipferrc/fm) and [StormForge Optimize – Controller](https://github.com/thestormforge/optimize-controller) to the list of Bubble Tea applications in production.

Add more Bubble Tea projects to README

---

examples/glamour/main.go
examples/spinner/main.go
examples/tui-daemon-combo/main.go

This PR further tidies up styling in examples and fixes a curious coloring bug in the Glamour example.

Tidy Up Styling in Examples

---

mouse.go
tea.go

This PR contains some housekeeping to remove linter warnings, which includes marking some false positives.

Satiate the linter

---

examples/send-msg/main.go
tea.go

This adds the ability to inject messages into the Bubble Tea update loop via `Program.Send(Msg)`. We believe this is important for interoperability with other libraries and programs.
If the program hasn't started or has exited this will be a no-op, so it's safe to call this regardless of the state of the program.
```go
p := tea.NewProgram(model)
go func() {
if err := p.Start(); err != nil {
fmt.Println("Uh oh", err)
os.Exit(1)
}
}()
p.Send(someMsg{value: "ta da!"});
```
Closes #25.

Send message to programs from outside the update loop

---

.gitignore
examples/go.sum
examples/list-default/main.go
examples/list-fancy/delegate.go
examples/list-fancy/main.go
examples/list-fancy/randomitems.go
examples/list-simple/main.go

Standard, simple, and fancy list examples.

Add list examples

---

README.md
tutorials/basics/README.md
tutorials/basics/main.go

fix: avoid global state

---

key.go
mouse.go
tea.go

This update adds a couple missing GoDocs and condenses an if statement.

Miscellaneous Lint

---

README.md
tutorials/basics/README.md
tutorials/basics/main.go
tutorials/commands/README.md

This is a minor housekeeping update to the tutorials which improves language, formatting and brings some sections up to date.

Tidy up tutorials

---

tea.go
tty.go

Tidying Up

---

nil_renderer_test.go
options_test.go
screen_test.go

test: nil renderer, options and screen

---

examples/result/main.go

This small PR updates the `result` example from a channel-based approach to the the new-ish [`StartReturningModel`](https://pkg.go.dev/github.com/charmbracelet/bubbletea@v0.19.3#Program.StartReturningModel).

Update result example to use StartReturningModel

---

examples/send-msg/main.go

Remove unused func from send-msg example

---

.github/dependabot.yml
examples/go.mod
examples/go.sum

some housekeeping:
- dependabot config for root go.mod, examples' go.mod and github actions
- go mod tidy on examples
- update bubbles on examples

chore: dependabot, go mod tidy, update bubbles

---

README.md

Hey! I made [clidle](https://github.com/ajeetdsouza/clidle), a Wordle game using Bubble Tea and Wish, I'd be grateful if you could check it out / feature it!

Add clidle under "Bubble Tea in the Wild"

---

examples/altscreen-toggle/main.go
examples/views/main.go

With CLICOLOR_FORCE set, this enables ANSI output even when writing to a non-terminal.

Use termenv's EnvColorProfile, which respects NO_COLOR and CLICOLOR_FORCE env vars

---

examples/go.mod
examples/go.sum
go.mod
go.sum
tutorials/go.sum

Bump lipgloss & termenv dependencies.

chore: bump lipgloss and termenv

---

README.md

Fix typos in root README.md

---

tea.go

forgot to update that paragraph of the docs.

docs: fixed mentions to exec.Command

---

examples/go.sum
go.mod
go.sum
tutorials/go.sum

refers to https://github.com/muesli/cancelreader/pull/9

feat: update cancelreader

---

README.md

- also fixed a handful of grammar-related items in the readme.
- closes: https://github.com/charmbracelet/bubbletea/issues/368

feat: add bubblezone to readme (closes #368)

---

.gitignore
README.md
tutorials/basics/README.md
tutorials/commands/README.md

docs: link to tutorial + general README edits

---

README.md

docs: add dns53 to bubbletea in the wild list

---

signals_unix.go
tty_unix.go

This simple commit enables building on IBM AIX. As for me this is the only change I need to make the package usable on AIX.

enable compilation on AIX

---

README.md

Hey everyone at Charm,
Hope this PR finds you well. 
Hope it is okay to add `circumflex` to the list of Bubble Tea in the Wild.

Add circumflex to Bubble Tea in the Wild

---

examples/split-editors/main.go

Closes https://github.com/charmbracelet/bubbletea/issues/366

Fix Split Editors resize issue

---

key.go
key_test.go

Fixes  #427.
cc @muesli @meowgorithm

keys: properly support the alt modifier

---

key.go

Support linux console F1-F5

---

README.md
tutorials/basics/README.md

Small wording and readability improvements to the README and basics tutorial.

docs: readme improvements

---

examples/glamour/main.go

Demonstrates using glamour styling within a scrolling viewport.

Use glamour-styled markdown within viewport

---

tea.go

Fix 1-indexing when entering alt screen

---

tea_test.go
tty.go

Two simple tests quitting and killing a `tea.Program` after its first render.

test: quit/kill model after the first render

---

examples/progress-download/main.go
examples/progress-download/tui.go

Some fixes I made while playing around with this example. Thanks!

Fixes for examples/progress-download

---

README.md

Finalize the attempt to sort the apps alphabetically.

docs: clean up and re-order 'Bubble Tea in the Wild'

---

tea.go

Common mistake (that I probably introduced myself in this case).

chore: remove incorrect space before nolint directives

---

nil_renderer.go
nil_renderer_test.go
renderer.go
standard_renderer.go
tea.go

Move output handling to renderer.

fix: move output handling to renderer

---

screen.go
tea.go

feat: add tea.ShowCursor, complementing tea.HideCursor

---

options.go
options_test.go
tea.go

Handle it like the other options, no need to make this special.

chore: make CatchPanics an option flag

---

tea.go

Groups struct members a bit more logically.

chore: reorganize Program struct

---

tea.go

This addresses one of the concerns in #299.

Update Program.Start docs to indicate it's a blocking operation

---

tea_test.go

test: add batchMsg test

---

tea_test.go

test: add sequenceMsg test

---

exec_test.go

Verify executing sub commands results in an error when they fail or the binary can't be started.

test: exec returning an error for invalid and failing commands

---

screen_test.go

Verifies all the screen commands work as expected.

test: add screen manipulation tests

---

nil_renderer_test.go

A bit pointless, but for coverage's sake.

test: complete nil renderer test

---

tea.go
tty.go

fix: timeout when waiting for CancelReader

---

tea.go

fix: ensure a final render before a clean shutdown

---

.github/dependabot.yml

chore: disable dependabot timer

---

README.md

docs: add Neon Modem Overdrive to "in the wild"

---

README.md

Signed-off-by: Pradeep Chhetri <pradeepchhetri4444@gmail.com>

Add chtop to the list built with bubbletea

---

README.md

Thanks for a really great framework!! ❤️ ❤️ 
I use Bubble Tea for a command line tool that automatically operates a terminal called [cLive](https://github.com/koki-develop/clive).
- https://github.com/koki-develop/clive
If you don't mind, let me add it to "Bubble Tea in the Wild". 🙏 🙏

add cLive to "Bubble Tea in the Wild"

---

examples/go.mod
examples/go.sum
go.mod
go.sum
tutorials/go.mod
tutorials/go.sum

Also bump various deps in tutorials and examples.

chore(deps): bump termenv and go-isatty

---

examples/credit-card-form/main.go
examples/help/main.go
examples/simple/main.go
examples/textarea/main.go
examples/tui-daemon-combo/main.go
mouse.go
options.go
tutorials/basics/README.md
tutorials/basics/main.go

Just wanted to help improve some of the docs 🤙

docs: fix typos and clean up comments

---

.github/workflows/examples.yml

this should prevent having to manually run `go mod tidy` in the `examples` folder.

feat(ci): auto go mod tidy examples

---

README.md

- add awslabs/eks-node-viewer project to "Bubble Tea in the Wild" list

feat(README): add eks-node-viewer to "Bubble Tea in the Wild" list 

---

README.md

I added a link to my countdown project in the Bubble Tea in the Wild section of the README.

docs: countdown to Bubble Tea in the Wild

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml

let me know if you think we can add/remove stuff from this...

docs: issue template

---

README.md

Add typioca to "Bubble Tea in the Wild" section

---

tea.go

Just a code organization PR. Found myself poking around for the different parts of `handler` whilst reading the source.

chore: group handler type and methods together

---

examples/autocomplete/main.go
examples/go.mod
examples/go.sum

https://github.com/charmbracelet/bubbletea/assets/42545625/a43877bb-b987-4d05-a7fd-6ecead72c58c

Autocompletion example

---

README.md

Thanks for all the great libraries 🎉

docs: add nom rss reader to bubble-tea-in-the-wild

---

commands.go
examples/set-window-title/main.go
screen.go
tea.go
tutorials/basics/main.go

Set the terminal window title using termenv.
Fixes: https://github.com/charmbracelet/bubbletea/issues/610

feat: add set-window-title command

---

examples/autocomplete/main.go
examples/go.mod

This PR styles and cleans up the autocomplete example for the suggestions feature on `textinput`

Cleanup autocomplete example

---

README.md

Hi 👋🏻 
I've created a terminal tool with use bubbletea, named "GAMA" (GitHub Actions Manager)
You can reach more information: [https://github.com/termkit/gama](https://github.com/termkit/gama)

Add gama into README.md

---

README.md

I modified name of my fractals-cli personal project (previous name was mandelbrot-cli)

modified name of fractals-cli personal project

---

README.md

An app that a created for my mentees. Fun and kinda hacker way to prepare for a coding interview.
App is showcase of non standard list usage, complex help, two screen navigation (list, play) and adaptive UI with UX trick (to small height warning).
Hope, you find it's funny and useful too.
https://github.com/rusinikita/trainer

docs(README): add trainer to Bubble Tea in the Wild

---

README.md

Add [json-log-viewer](https://github.com/hedhyw/json-log-viewer) to [Bubble Tea in the Wild](https://github.com/charmbracelet/bubbletea#bubble-tea-in-the-wild).

docs: add interactive viewer for JSON logs to Readme

---

.github/dependabot.yml

Change dependabot commit message to `chore` from `feat`.

Change dependabot commit message to `chore` from `feat`

---

README.md

Hi! I've used Bubble Tea in a few different projects, but finally have one that feels right to add to the list of example programs. This PR adds a link to [gabe565/ascii-movie](https://github.com/gabe565/ascii-movie) to the readme.
ASCII Movie plays the Star Wars telnet movie locally, over SSH, or over Telnet and uses Bubble Tea for its TUI.

docs(readme): Add ascii-movie to 'Bubble Tea in the Wild' section

---

commands_test.go

Fixes: 305d5b285f4b (chore: optimize batches with one item (#875))

fix(tests): single batch cmd

---

examples/table-resize/main.go

Example adds a Lip Gloss table rendered with height and width set to the screen.

Lip Gloss table resizing demo

---

README.md

A little TUI I have written with bubbletea - [nachrichten](https://github.com/zMoooooritz/nachrichten)

docs: add nachrichten to Bubble Tea in the Wild

---

README.md

- **docs(readme): add ChatGPTUI link**

Add ChatGPTUI to README

---

README.md

docs: update readme with new chatgpt-tui

---

examples/altscreen-toggle/main.go
examples/go.mod
examples/simple/main_test.go
examples/views/main.go

Lip Gloss abstracts away the color profiles logic and results in less lines

chore(examples): use lipgloss everywhere possible

---

README.md

[Plandex](https://github.com/plandex-ai/plandex) is a terminal-based AI coding engine for complex tasks. It makes significant use of BubbleTea in multiple TUIs. Thank you, this library has been a godsend!

Add Plandex (terminal-based AI coding engine) to 'In the Wild' section

---

README.md

1 addition to "in the Wild":
[prs](https://github.com/dhth/prs): lets you stay updated on PRs without leaving the terminal
Thanks!

docs: add prs to "in the Wild"

---

tea.go

fix: deadlock condition on model init panic

---

.golangci-soft.yml
key.go
mouse.go

Just doing this to keep this stuff from showing up in other PRs.

chore(lint): minor lint-related improvements

---

README.md

Pug is a task manager for terraform: https://github.com/leg100/pug
It's been refreshing working with bubbletea, thank you for all your hard work.

docs: add pug to "in the wild"

---

inputreader_windows.go
key_windows.go

Windows alt-screen-buffer changes trigger window-size-events causing Bubble Tea to send a new event even if the window size is the same as before. This simply checks if the window size is the same before bubbling it to the model.
Fixes: https://github.com/charmbracelet/bubbletea/issues/1019

Prevent multiple window-size-events from firing on Windows

---

examples/chat/main.go
examples/go.mod
examples/go.sum

fix(examples): keys shouldn't be routed to viewport in chat example

---

examples/simple/main_test.go
options.go
screen_test.go
standard_renderer.go
tea.go

The ferocious renderer is now opt-in. This commit adds a new option `WithFerociousRenderer` that enables the ferocious renderer.

(v2) feat: make the ferocious renderer opt-in

---

xterm.go

chore: fix function name in comment

---

examples/chat/main.go

Example now demonstrates working with `tea.WindowSizeMsg` and fixes cutting content experienced in https://github.com/charmbracelet/bubbles/issues/644
demo:
https://github.com/user-attachments/assets/3a6f25d0-b57f-4729-9298-74b989ea55ff

feat(example): resize chat example based on window

---

examples/README.md

I reviewed the entire repository, no more typos found in docs. 
Hope this helps streamline the project!
Best regards,
Bilogweb3

chore: correct typos docs

---

tutorials/commands/README.md

When read without the comma, it gives me the impression that there are two tutorials covering the topic of commands.  
(I instantly go back, thinking, "Wait, what did I miss? Where is the first one about commands?")  
However, the intention is to clarify that this is the second tutorial in the series of Bubble Tea tutorials.

fix: Insert comma to avoid possible missundertood.

---

examples/doom-fire/main.go

feat(examples): add doom-fire example

---

commands.go

make it consistent with the other request commands

fix: make it a command

---

examples/autocomplete/main.go
examples/go.mod
examples/go.sum

This revision makes it way clearer when completion is and isn't available in the autocomplete example. Closes #1337.

fix(examples): improve autocomplete ux

---

tty.go
tutorials/basics/README.md

docs: tidy
